// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace TestViewControllerInViewController
{
	public partial class FilterViewController : NSViewController
	{
		public FilterViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			Remove.Activated += (sender, e) => {

				((ViewController)ParentViewController).RemoveMyView(this);

				RemoveFromParentViewController();
				Dispose();
			};
		}
	}
}
